{
 "title": "Vertica",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "host", "query": "vertica_node_node_state_int" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes (UP)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum(vertica_node_node_state_int{node_state=\"UP\"}) by (node_name))"
    }
   ]
  },
  {
   "title": "Fault Tolerance (min)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(vertica_system_current_fault_tolerance{})"
    }
   ]
  },
  {
   "title": "Load Balance Policy",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "min(vertica_load_balance_policy{}) by (load_balance_policy)",
     "legendFormat": "{{load_balance_policy}}"
    }
   ]
  },
  {
   "title": "Rejections (period)",
   "type": "singlestat",
   "description": "Rejections over time interval",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(vertica_resource_rejections_rejection_count{}[$__range])) "
    }
   ]
  },
  {
   "title": "Errors (period)",
   "type": "singlestat",
   "description": "Error messages by seleced period",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg without (instance, host) (increase(vertica_error_messages_count{}[$__range])))"
    }
   ]
  },
  {
   "title": "Vertica node state",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "sum(vertica_node_node_state_int{}) by (node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Max CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(procstat_cpu_usage{host=~\"$host\", process_name=\"vertica\"}/ on (host) system_n_cpus{host=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Max Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(procstat_memory_usage{host=~\"$host\", process_name=\"vertica\"})"
    }
   ]
  },
  {
   "title": "Max WOS Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(vertica_resource_usage_wos_used_bytes{})"
    }
   ]
  },
  {
   "title": "Max ROS Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(vertica_resource_usage_ros_used_bytes{})"
    }
   ]
  },
  {
   "title": "Active Sessions",
   "type": "singlestat",
   "description": "Active User Sessions",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vertica_query_active_user_session_count)"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load Average 1min",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "system_load1{host=~\"$host\"}",
       "legendFormat": "{{host}}"
      },
      {
       "expr": "node_load1{instance=~\"$host\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "disk_used{host=~\"$host\", path!~\"/boot\"}",
       "legendFormat": "{{host}} - {{path}}"
      }
     ]
    }
   ]
  },
  { "title": "Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Sessions count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "vertica_sessions_count", "legendFormat": "{{node_name}} - {{user_name}}" }
   ]
  },
  {
   "title": "Executed Query Count (rps) / Running Query Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vertica_query_executed_query_count[1m])",
     "legendFormat": "Executed - {{node_name}}"
    },
    {
     "expr": "vertica_query_running_query_count",
     "legendFormat": "Running - {{node_name}}"
    }
   ]
  },
  {
   "title": "Active User Sessions (by Node) / New System + User sessions (rpm)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vertica_query_active_user_session_count",
     "legendFormat": "Active sessions - {{node_name}}"
    },
    {
     "expr": "sum(increase(vertica_query_total_user_session_count[1m]))",
     "legendFormat": "User sessions (rpm)"
    },
    {
     "expr": "sum(increase(vertica_query_total_system_session_count[1m]))",
     "legendFormat": "System sessions (rpm)"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Request Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(vertica_resource_usage_request_count) by (node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Active Thread Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(vertica_resource_usage_active_thread_count) by (node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Memory Requested",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "max(vertica_resource_usage_memory_requested_kb) by (node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "WOS Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max(vertica_resource_usage_wos_used_bytes) by (node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "WOS Row Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(vertica_resource_usage_wos_row_count) by (node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "ROS Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max(vertica_resource_usage_ros_used_bytes) by (node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "ROS Row Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(vertica_resource_usage_ros_row_count) by (node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Vertica Memory Usage (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max(procstat_memory_usage{host=~\"$host\", process_name=\"vertica\"}) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Vertica CPU Usage (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 41 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "procstat_cpu_usage{host=~\"$host\", process_name=\"vertica\"}/ on (host) system_n_cpus{host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Storage Usage (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "vertica_storage_usage_usage_percent",
     "legendFormat": "{{host}} - {{node_name}}"
    }
   ]
  },
  {
   "title": "Resource - Rejections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Vertica Resource Rejection Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(vertica_resource_rejections_rejection_count{}[1m])) by (pool_name, resource_type)",
       "legendFormat": "{{pool_name}} - {{resource_type}}"
      }
     ]
    },
    {
     "title": "Vertica Resource Rejection Count",
     "type": "table",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 10 },
     "targets": [
      {
       "expr": "vertica_resource_rejections_rejection_count{}",
       "legendFormat": "{{pool_name}} - {{resource_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error Messages (by period)",
     "type": "graph",
     "description": "PS: Avg() - deduplication of same metrics",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg without (instance, host) (increase(vertica_error_messages_count[1m]))",
       "legendFormat": "[{{error_level}}] {{user_name}} - {{message}}"
      }
     ]
    },
    {
     "title": "Error Messages",
     "type": "table",
     "description": "PS: Avg() - deduplication of same metrics",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "avg without (instance, host) (vertica_error_messages_count)",
       "legendFormat": "[{{error_level}}] {{user_name}} - {{message}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource - Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "General Memory Borrowed",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "format": "deckbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "vertica_resource_pool_general_memory_borrowed_kb>0",
       "legendFormat": "{{node_name}} {{pool_name}}"
      }
     ]
    },
    {
     "title": "Memory In Use",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "format": "deckbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "vertica_resource_pool_memory_inuse_kb > 0",
       "legendFormat": "{{node_name}} {{pool_name}}"
      }
     ]
    },
    {
     "title": "General Memory Borrowed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "expr": "vertica_resource_pool_general_memory_borrowed_kb",
       "legendFormat": "{{node_name}} {{pool_name}}"
      }
     ]
    },
    {
     "title": "Memory In Use",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "expr": "vertica_resource_pool_memory_inuse_kb",
       "legendFormat": "{{node_name}} {{pool_name}}"
      }
     ]
    },
    {
     "title": "Resource Pool - Running Query Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vertica_resource_pool_running_query_count) by (pool_name)",
       "legendFormat": "{{node_name}} {{pool_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Querues - Requested Memory / Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "expr": "vertica_resource_queues_memory_requested_kb_total",
       "legendFormat": "{{node_name}} - {{pool_name}}"
      },
      {
       "expr": "sum(vertica_resource_queues_memory_requested_kb_total) by (node_name)",
       "legendFormat": "Total - {{node_name}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Containers - Delete Vector Count",
     "type": "graph",
     "description": "A high number of delete vectors indicates the cluster is in a troubled state. \n\ndeleted_row_count > total_row_count*0.05",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vertica_storage_containers_delete_vector_count) by (projection_name, schema_name)",
       "legendFormat": "{{schema_name}} {{projection_name}}"
      }
     ]
    },
    {
     "title": "Storage Containers - ROS Count",
     "type": "table",
     "description": "Monitor the Number of ROS Containers Vertica has an upper threshold of 1024 ROS containers per projection. If the number of ROS containers in your database grows too large, it can negatively affect performance. \n\nA high number (over 500) of ROS containers indicates a problem with the PARTITION BY clauses of your tables. It can also indicate that the merging process is not functioning. For more information, see Vertica Partitions: The FAQs in the Vertica Knowledge Base.",
     "gridPos": { "h": 9, "w": 15, "x": 9, "y": 22 },
     "targets": [
      {
       "expr": "sum(vertica_projection_storage_ros_count) by (node_name, projection_name, projection_schema)",
       "legendFormat": "{{projection_name}} {{projection_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Vertica Exporter Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Exporter Scrape Duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "pg_exporter_last_scrape_duration_seconds{}",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  }
 ]
}